version: '3.5'
services:
 web:
  image: python:3.7
  ports:
   - "8080:8000"
  volumes:
   - .:/app
  environment:
    - MONGO_HOST=mongodb
    - MONGO_PORT=27017
  working_dir: /app
  command: >
    bash -c "pip install -r requirements_prod.txt
    && gunicorn -w 2 --bind 0.0.0.0:8000 app.wsgi:app"
  depends_on:
    - mongodb
 mongodb:
  image: mongo:latest
  container_name: mongodb
  volumes:
   - ./data/db:/data/db
  ports:
   - 27017:27017
  command: mongod --smallfiles # --logpath=/dev/null # --quiet
