r'''
Bare bones example of Flask
'''

from flask import Flask

app = Flask(__name__)


@app.route('/')
def get_all():
    return '''<!DOCTYPE html>
<html>
<body>
<h1>Flask Test</h1>
<p>This is generated by Flask</p>
</body>
</html>
'''


if __name__ == "__main__":
    app.run(debug=True)
