r'''
Bare bones example of Flask
'''

from flask import Flask

app = Flask(__name__)


@app.route('/')
def index():
    return '''<!DOCTYPE html>
<html>
<body>
<h1>Flask Test</h1>
<p>This is generated by Flask</p>
<a href="/link">Click here to go to the link page</a>
</body>
</html>
'''

@app.route('/link')
def link():
    return '''<!DOCTYPE html>
<html>
<body>
<h1>Flask Test: Link page</h1>
<p>This is the link page generated by Flask</p>
<a href="/">Go back to the index</a>
</body>
</html>
'''


if __name__ == "__main__":
    app.run(debug=True)
